using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PracticalTDD.Dependencies
{
    class Monster
    {
        public void DoSomething()
        {


            Console.WriteLine("ACT I");
            Console.WriteLine("");
            Console.WriteLine("SCENE I. Elsinore. A platform before the castle.");
            Console.WriteLine("");
            Console.WriteLine("FRANCISCO at his post. Enter to him BERNARDO");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Who\'s there?");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("Nay, answer me: stand, and unfold yourself.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Long live the king!");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("Bernardo?");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("He.");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("You come most carefully upon your hour.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("\'Tis now struck twelve; get thee to bed, Francisco.");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("For this relief much thanks: \'tis bitter cold,");
            Console.WriteLine("And I am sick at heart.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Have you had quiet guard?");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("Not a mouse stirring.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Well, good night.");
            Console.WriteLine("If you do meet Horatio and Marcellus,");
            Console.WriteLine("The rivals of my watch, bid them make haste.");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("I think I hear them. Stand, ho! Who\'s there?");
            Console.WriteLine("Enter HORATIO and MARCELLUS");
            Console.WriteLine("");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Friends to this ground.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("And liegemen to the Dane.");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("Give you good night.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("O, farewell, honest soldier:");
            Console.WriteLine("Who hath relieved you?");
            Console.WriteLine("FRANCISCO");
            Console.WriteLine("Bernardo has my place.");
            Console.WriteLine("Give you good night.");
            Console.WriteLine("Exit");
            Console.WriteLine("");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Holla! Bernardo!");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Say,");
            Console.WriteLine("What, is Horatio there?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("A piece of him.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Welcome, Horatio: welcome, good Marcellus.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("What, has this thing appear\'d again to-night?");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("I have seen nothing.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Horatio says \'tis but our fantasy,");
            Console.WriteLine("And will not let belief take hold of him");
            Console.WriteLine("Touching this dreaded sight, twice seen of us:");
            Console.WriteLine("Therefore I have entreated him along");
            Console.WriteLine("With us to watch the minutes of this night;");
            Console.WriteLine("That if again this apparition come,");
            Console.WriteLine("He may approve our eyes and speak to it.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Tush, tush, \'twill not appear.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Sit down awhile;");
            Console.WriteLine("And let us once again assail your ears,");
            Console.WriteLine("That are so fortified against our story");
            Console.WriteLine("What we have two nights seen.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Well, sit we down,");
            Console.WriteLine("And let us hear Bernardo speak of this.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Last night of all,");
            Console.WriteLine("When yond same star that\'s westward from the pole");
            Console.WriteLine("Had made his course to illume that part of heaven");
            Console.WriteLine("Where now it burns, Marcellus and myself,");
            Console.WriteLine("The bell then beating one,--");
            Console.WriteLine("Enter Ghost");
            Console.WriteLine("");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Peace, break thee off; look, where it comes again!");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("In the same figure, like the king that\'s dead.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Thou art a scholar; speak to it, Horatio.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("Looks it not like the king? mark it, Horatio.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Most like: it harrows me with fear and wonder.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("It would be spoke to.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Question it, Horatio.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("What art thou that usurp\'st this time of night,");
            Console.WriteLine("Together with that fair and warlike form");
            Console.WriteLine("In which the majesty of buried Denmark");
            Console.WriteLine("Did sometimes march? by heaven I charge thee, speak!");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("It is offended.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("See, it stalks away!");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Stay! speak, speak! I charge thee, speak!");
            Console.WriteLine("Exit Ghost");
            Console.WriteLine("");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("\'Tis gone, and will not answer.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("How now, Horatio! you tremble and look pale:");
            Console.WriteLine("Is not this something more than fantasy?");
            Console.WriteLine("What think you on\'t?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Before my God, I might not this believe");
            Console.WriteLine("Without the sensible and true avouch");
            Console.WriteLine("Of mine own eyes.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Is it not like the king?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("As thou art to thyself:");
            Console.WriteLine("Such was the very armour he had on");
            Console.WriteLine("When he the ambitious Norway combated;");
            Console.WriteLine("So frown\'d he once, when, in an angry parle,");
            Console.WriteLine("He smote the sledded Polacks on the ice.");
            Console.WriteLine("\'Tis strange.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Thus twice before, and jump at this dead hour,");
            Console.WriteLine("With martial stalk hath he gone by our watch.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("In what particular thought to work I know not;");
            Console.WriteLine("But in the gross and scope of my opinion,");
            Console.WriteLine("This bodes some strange eruption to our state.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Good now, sit down, and tell me, he that knows,");
            Console.WriteLine("Why this same strict and most observant watch");
            Console.WriteLine("So nightly toils the subject of the land,");
            Console.WriteLine("And why such daily cast of brazen cannon,");
            Console.WriteLine("And foreign mart for implements of war;");
            Console.WriteLine("Why such impress of shipwrights, whose sore task");
            Console.WriteLine("Does not divide the Sunday from the week;");
            Console.WriteLine("What might be toward, that this sweaty haste");
            Console.WriteLine("Doth make the night joint-labourer with the day:");
            Console.WriteLine("Who is\'t that can inform me?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("That can I;");
            Console.WriteLine("At least, the whisper goes so. Our last king,");
            Console.WriteLine("Whose image even but now appear\'d to us,");
            Console.WriteLine("Was, as you know, by Fortinbras of Norway,");
            Console.WriteLine("Thereto prick\'d on by a most emulate pride,");
            Console.WriteLine("Dared to the combat; in which our valiant Hamlet--");
            Console.WriteLine("For so this side of our known world esteem\'d him--");
            Console.WriteLine("Did slay this Fortinbras; who by a seal\'d compact,");
            Console.WriteLine("Well ratified by law and heraldry,");
            Console.WriteLine("Did forfeit, with his life, all those his lands");
            Console.WriteLine("Which he stood seized of, to the conqueror:");
            Console.WriteLine("Against the which, a moiety competent");
            Console.WriteLine("Was gaged by our king; which had return\'d");
            Console.WriteLine("To the inheritance of Fortinbras,");
            Console.WriteLine("Had he been vanquisher; as, by the same covenant,");
            Console.WriteLine("And carriage of the article design\'d,");
            Console.WriteLine("His fell to Hamlet. Now, sir, young Fortinbras,");
            Console.WriteLine("Of unimproved mettle hot and full,");
            Console.WriteLine("Hath in the skirts of Norway here and there");
            Console.WriteLine("Shark\'d up a list of lawless resolutes,");
            Console.WriteLine("For food and diet, to some enterprise");
            Console.WriteLine("That hath a stomach in\'t; which is no other--");
            Console.WriteLine("As it doth well appear unto our state--");
            Console.WriteLine("But to recover of us, by strong hand");
            Console.WriteLine("And terms compulsatory, those foresaid lands");
            Console.WriteLine("So by his father lost: and this, I take it,");
            Console.WriteLine("Is the main motive of our preparations,");
            Console.WriteLine("The source of this our watch and the chief head");
            Console.WriteLine("Of this post-haste and romage in the land.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("I think it be no other but e\'en so:");
            Console.WriteLine("Well may it sort that this portentous figure");
            Console.WriteLine("Comes armed through our watch; so like the king");
            Console.WriteLine("That was and is the question of these wars.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("A mote it is to trouble the mind\'s eye.");
            Console.WriteLine("In the most high and palmy state of Rome,");
            Console.WriteLine("A little ere the mightiest Julius fell,");
            Console.WriteLine("The graves stood tenantless and the sheeted dead");
            Console.WriteLine("Did squeak and gibber in the Roman streets:");
            Console.WriteLine("As stars with trains of fire and dews of blood,");
            Console.WriteLine("Disasters in the sun; and the moist star");
            Console.WriteLine("Upon whose influence Neptune\'s empire stands");
            Console.WriteLine("Was sick almost to doomsday with eclipse:");
            Console.WriteLine("And even the like precurse of fierce events,");
            Console.WriteLine("As harbingers preceding still the fates");
            Console.WriteLine("And prologue to the omen coming on,");
            Console.WriteLine("Have heaven and earth together demonstrated");
            Console.WriteLine("Unto our climatures and countrymen.--");
            Console.WriteLine("But soft, behold! lo, where it comes again!");
            Console.WriteLine("Re-enter Ghost");
            Console.WriteLine("");
            Console.WriteLine("I\'ll cross it, though it blast me. Stay, illusion!");
            Console.WriteLine("If thou hast any sound, or use of voice,");
            Console.WriteLine("Speak to me:");
            Console.WriteLine("If there be any good thing to be done,");
            Console.WriteLine("That may to thee do ease and grace to me,");
            Console.WriteLine("Speak to me:");
            Console.WriteLine("Cock crows");
            Console.WriteLine("");
            Console.WriteLine("If thou art privy to thy country\'s fate,");
            Console.WriteLine("Which, happily, foreknowing may avoid, O, speak!");
            Console.WriteLine("Or if thou hast uphoarded in thy life");
            Console.WriteLine("Extorted treasure in the womb of earth,");
            Console.WriteLine("For which, they say, you spirits oft walk in death,");
            Console.WriteLine("Speak of it: stay, and speak! Stop it, Marcellus.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Shall I strike at it with my partisan?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Do, if it will not stand.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("\'Tis here!");
            Console.WriteLine("HORATIO");
            Console.WriteLine("\'Tis here!");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("\'Tis gone!");
            Console.WriteLine("Exit Ghost");
            Console.WriteLine("");
            Console.WriteLine("We do it wrong, being so majestical,");
            Console.WriteLine("To offer it the show of violence;");
            Console.WriteLine("For it is, as the air, invulnerable,");
            Console.WriteLine("And our vain blows malicious mockery.");
            Console.WriteLine("BERNARDO");
            Console.WriteLine("It was about to speak, when the cock crew.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("And then it started like a guilty thing");
            Console.WriteLine("Upon a fearful summons. I have heard,");
            Console.WriteLine("The cock, that is the trumpet to the morn,");
            Console.WriteLine("Doth with his lofty and shrill-sounding throat");
            Console.WriteLine("Awake the god of day; and, at his warning,");
            Console.WriteLine("Whether in sea or fire, in earth or air,");
            Console.WriteLine("The extravagant and erring spirit hies");
            Console.WriteLine("To his confine: and of the truth herein");
            Console.WriteLine("This present object made probation.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("It faded on the crowing of the cock.");
            Console.WriteLine("Some say that ever \'gainst that season comes");
            Console.WriteLine("Wherein our Saviour\'s birth is celebrated,");
            Console.WriteLine("The bird of dawning singeth all night long:");
            Console.WriteLine("And then, they say, no spirit dares stir abroad;");
            Console.WriteLine("The nights are wholesome; then no planets strike,");
            Console.WriteLine("No fairy takes, nor witch hath power to charm,");
            Console.WriteLine("So hallow\'d and so gracious is the time.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("So have I heard and do in part believe it.");
            Console.WriteLine("But, look, the morn, in russet mantle clad,");
            Console.WriteLine("Walks o\'er the dew of yon high eastward hill:");
            Console.WriteLine("Break we our watch up; and by my advice,");
            Console.WriteLine("Let us impart what we have seen to-night");
            Console.WriteLine("Unto young Hamlet; for, upon my life,");
            Console.WriteLine("This spirit, dumb to us, will speak to him.");
            Console.WriteLine("Do you consent we shall acquaint him with it,");
            Console.WriteLine("As needful in our loves, fitting our duty?");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Let\'s do\'t, I pray; and I this morning know");
            Console.WriteLine("Where we shall find him most conveniently.");
            Console.WriteLine("Exeunt");
            Console.WriteLine("");
            Console.WriteLine("SCENE II. A room of state in the castle.");
            Console.WriteLine("");
            Console.WriteLine("Enter KING CLAUDIUS, QUEEN GERTRUDE, HAMLET, POLONIUS, LAERTES, VOLTIMAND, CORNELIUS, Lords, and Attendants");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("Though yet of Hamlet our dear brother\'s death");
            Console.WriteLine("The memory be green, and that it us befitted");
            Console.WriteLine("To bear our hearts in grief and our whole kingdom");
            Console.WriteLine("To be contracted in one brow of woe,");
            Console.WriteLine("Yet so far hath discretion fought with nature");
            Console.WriteLine("That we with wisest sorrow think on him,");
            Console.WriteLine("Together with remembrance of ourselves.");
            Console.WriteLine("Therefore our sometime sister, now our queen,");
            Console.WriteLine("The imperial jointress to this warlike state,");
            Console.WriteLine("Have we, as \'twere with a defeated joy,--");
            Console.WriteLine("With an auspicious and a dropping eye,");
            Console.WriteLine("With mirth in funeral and with dirge in marriage,");
            Console.WriteLine("In equal scale weighing delight and dole,--");
            Console.WriteLine("Taken to wife: nor have we herein barr\'d");
            Console.WriteLine("Your better wisdoms, which have freely gone");
            Console.WriteLine("With this affair along. For all, our thanks.");
            Console.WriteLine("Now follows, that you know, young Fortinbras,");
            Console.WriteLine("Holding a weak supposal of our worth,");
            Console.WriteLine("Or thinking by our late dear brother\'s death");
            Console.WriteLine("Our state to be disjoint and out of frame,");
            Console.WriteLine("Colleagued with the dream of his advantage,");
            Console.WriteLine("He hath not fail\'d to pester us with message,");
            Console.WriteLine("Importing the surrender of those lands");
            Console.WriteLine("Lost by his father, with all bonds of law,");
            Console.WriteLine("To our most valiant brother. So much for him.");
            Console.WriteLine("Now for ourself and for this time of meeting:");
            Console.WriteLine("Thus much the business is: we have here writ");
            Console.WriteLine("To Norway, uncle of young Fortinbras,--");
            Console.WriteLine("Who, impotent and bed-rid, scarcely hears");
            Console.WriteLine("Of this his nephew\'s purpose,--to suppress");
            Console.WriteLine("His further gait herein; in that the levies,");
            Console.WriteLine("The lists and full proportions, are all made");
            Console.WriteLine("Out of his subject: and we here dispatch");
            Console.WriteLine("You, good Cornelius, and you, Voltimand,");
            Console.WriteLine("For bearers of this greeting to old Norway;");
            Console.WriteLine("Giving to you no further personal power");
            Console.WriteLine("To business with the king, more than the scope");
            Console.WriteLine("Of these delated articles allow.");
            Console.WriteLine("Farewell, and let your haste commend your duty.");
            Console.WriteLine("CORNELIUS VOLTIMAND");
            Console.WriteLine("In that and all things will we show our duty.");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("We doubt it nothing: heartily farewell.");
            Console.WriteLine("Exeunt VOLTIMAND and CORNELIUS");
            Console.WriteLine("");
            Console.WriteLine("And now, Laertes, what\'s the news with you?");
            Console.WriteLine("You told us of some suit; what is\'t, Laertes?");
            Console.WriteLine("You cannot speak of reason to the Dane,");
            Console.WriteLine("And loose your voice: what wouldst thou beg, Laertes,");
            Console.WriteLine("That shall not be my offer, not thy asking?");
            Console.WriteLine("The head is not more native to the heart,");
            Console.WriteLine("The hand more instrumental to the mouth,");
            Console.WriteLine("Than is the throne of Denmark to thy father.");
            Console.WriteLine("What wouldst thou have, Laertes?");
            Console.WriteLine("LAERTES");
            Console.WriteLine("My dread lord,");
            Console.WriteLine("Your leave and favour to return to France;");
            Console.WriteLine("From whence though willingly I came to Denmark,");
            Console.WriteLine("To show my duty in your coronation,");
            Console.WriteLine("Yet now, I must confess, that duty done,");
            Console.WriteLine("My thoughts and wishes bend again toward France");
            Console.WriteLine("And bow them to your gracious leave and pardon.");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("Have you your father\'s leave? What says Polonius?");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("He hath, my lord, wrung from me my slow leave");
            Console.WriteLine("By laboursome petition, and at last");
            Console.WriteLine("Upon his will I seal\'d my hard consent:");
            Console.WriteLine("I do beseech you, give him leave to go.");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("Take thy fair hour, Laertes; time be thine,");
            Console.WriteLine("And thy best graces spend it at thy will!");
            Console.WriteLine("But now, my cousin Hamlet, and my son,--");
            Console.WriteLine("HAMLET");
            Console.WriteLine("[Aside] A little more than kin, and less than kind.");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("How is it that the clouds still hang on you?");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Not so, my lord; I am too much i\' the sun.");
            Console.WriteLine("QUEEN GERTRUDE");
            Console.WriteLine("Good Hamlet, cast thy nighted colour off,");
            Console.WriteLine("And let thine eye look like a friend on Denmark.");
            Console.WriteLine("Do not for ever with thy vailed lids");
            Console.WriteLine("Seek for thy noble father in the dust:");
            Console.WriteLine("Thou know\'st \'tis common; all that lives must die,");
            Console.WriteLine("Passing through nature to eternity.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Ay, madam, it is common.");
            Console.WriteLine("QUEEN GERTRUDE");
            Console.WriteLine("If it be,");
            Console.WriteLine("Why seems it so particular with thee?");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Seems, madam! nay it is; I know not \'seems.\'");
            Console.WriteLine("\'Tis not alone my inky cloak, good mother,");
            Console.WriteLine("Nor customary suits of solemn black,");
            Console.WriteLine("Nor windy suspiration of forced breath,");
            Console.WriteLine("No, nor the fruitful river in the eye,");
            Console.WriteLine("Nor the dejected \'havior of the visage,");
            Console.WriteLine("Together with all forms, moods, shapes of grief,");
            Console.WriteLine("That can denote me truly: these indeed seem,");
            Console.WriteLine("For they are actions that a man might play:");
            Console.WriteLine("But I have that within which passeth show;");
            Console.WriteLine("These but the trappings and the suits of woe.");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("\'Tis sweet and commendable in your nature, Hamlet,");
            Console.WriteLine("To give these mourning duties to your father:");
            Console.WriteLine("But, you must know, your father lost a father;");
            Console.WriteLine("That father lost, lost his, and the survivor bound");
            Console.WriteLine("In filial obligation for some term");
            Console.WriteLine("To do obsequious sorrow: but to persever");
            Console.WriteLine("In obstinate condolement is a course");
            Console.WriteLine("Of impious stubbornness; \'tis unmanly grief;");
            Console.WriteLine("It shows a will most incorrect to heaven,");
            Console.WriteLine("A heart unfortified, a mind impatient,");
            Console.WriteLine("An understanding simple and unschool\'d:");
            Console.WriteLine("For what we know must be and is as common");
            Console.WriteLine("As any the most vulgar thing to sense,");
            Console.WriteLine("Why should we in our peevish opposition");
            Console.WriteLine("Take it to heart? Fie! \'tis a fault to heaven,");
            Console.WriteLine("A fault against the dead, a fault to nature,");
            Console.WriteLine("To reason most absurd: whose common theme");
            Console.WriteLine("Is death of fathers, and who still hath cried,");
            Console.WriteLine("From the first corse till he that died to-day,");
            Console.WriteLine("\'This must be so.\' We pray you, throw to earth");
            Console.WriteLine("This unprevailing woe, and think of us");
            Console.WriteLine("As of a father: for let the world take note,");
            Console.WriteLine("You are the most immediate to our throne;");
            Console.WriteLine("And with no less nobility of love");
            Console.WriteLine("Than that which dearest father bears his son,");
            Console.WriteLine("Do I impart toward you. For your intent");
            Console.WriteLine("In going back to school in Wittenberg,");
            Console.WriteLine("It is most retrograde to our desire:");
            Console.WriteLine("And we beseech you, bend you to remain");
            Console.WriteLine("Here, in the cheer and comfort of our eye,");
            Console.WriteLine("Our chiefest courtier, cousin, and our son.");
            Console.WriteLine("QUEEN GERTRUDE");
            Console.WriteLine("Let not thy mother lose her prayers, Hamlet:");
            Console.WriteLine("I pray thee, stay with us; go not to Wittenberg.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I shall in all my best obey you, madam.");
            Console.WriteLine("KING CLAUDIUS");
            Console.WriteLine("Why, \'tis a loving and a fair reply:");
            Console.WriteLine("Be as ourself in Denmark. Madam, come;");
            Console.WriteLine("This gentle and unforced accord of Hamlet");
            Console.WriteLine("Sits smiling to my heart: in grace whereof,");
            Console.WriteLine("No jocund health that Denmark drinks to-day,");
            Console.WriteLine("But the great cannon to the clouds shall tell,");
            Console.WriteLine("And the king\'s rouse the heavens all bruit again,");
            Console.WriteLine("Re-speaking earthly thunder. Come away.");
            Console.WriteLine("Exeunt all but HAMLET");
            Console.WriteLine("");
            Console.WriteLine("HAMLET");
            Console.WriteLine("O, that this too too solid flesh would melt");
            Console.WriteLine("Thaw and resolve itself into a dew!");
            Console.WriteLine("Or that the Everlasting had not fix\'d");
            Console.WriteLine("His canon \'gainst self-slaughter! O God! God!");
            Console.WriteLine("How weary, stale, flat and unprofitable,");
            Console.WriteLine("Seem to me all the uses of this world!");
            Console.WriteLine("Fie on\'t! ah fie! \'tis an unweeded garden,");
            Console.WriteLine("That grows to seed; things rank and gross in nature");
            Console.WriteLine("Possess it merely. That it should come to this!");
            Console.WriteLine("But two months dead: nay, not so much, not two:");
            Console.WriteLine("So excellent a king; that was, to this,");
            Console.WriteLine("Hyperion to a satyr; so loving to my mother");
            Console.WriteLine("That he might not beteem the winds of heaven");
            Console.WriteLine("Visit her face too roughly. Heaven and earth!");
            Console.WriteLine("Must I remember? why, she would hang on him,");
            Console.WriteLine("As if increase of appetite had grown");
            Console.WriteLine("By what it fed on: and yet, within a month--");
            Console.WriteLine("Let me not think on\'t--Frailty, thy name is woman!--");
            Console.WriteLine("A little month, or ere those shoes were old");
            Console.WriteLine("With which she follow\'d my poor father\'s body,");
            Console.WriteLine("Like Niobe, all tears:--why she, even she--");
            Console.WriteLine("O, God! a beast, that wants discourse of reason,");
            Console.WriteLine("Would have mourn\'d longer--married with my uncle,");
            Console.WriteLine("My father\'s brother, but no more like my father");
            Console.WriteLine("Than I to Hercules: within a month:");
            Console.WriteLine("Ere yet the salt of most unrighteous tears");
            Console.WriteLine("Had left the flushing in her galled eyes,");
            Console.WriteLine("She married. O, most wicked speed, to post");
            Console.WriteLine("With such dexterity to incestuous sheets!");
            Console.WriteLine("It is not nor it cannot come to good:");
            Console.WriteLine("But break, my heart; for I must hold my tongue.");
            Console.WriteLine("Enter HORATIO, MARCELLUS, and BERNARDO");
            Console.WriteLine("");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Hail to your lordship!");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I am glad to see you well:");
            Console.WriteLine("Horatio,--or I do forget myself.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("The same, my lord, and your poor servant ever.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Sir, my good friend; I\'ll change that name with you:");
            Console.WriteLine("And what make you from Wittenberg, Horatio? Marcellus?");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("My good lord--");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I am very glad to see you. Good even, sir.");
            Console.WriteLine("But what, in faith, make you from Wittenberg?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("A truant disposition, good my lord.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I would not hear your enemy say so,");
            Console.WriteLine("Nor shall you do mine ear that violence,");
            Console.WriteLine("To make it truster of your own report");
            Console.WriteLine("Against yourself: I know you are no truant.");
            Console.WriteLine("But what is your affair in Elsinore?");
            Console.WriteLine("We\'ll teach you to drink deep ere you depart.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("My lord, I came to see your father\'s funeral.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I pray thee, do not mock me, fellow-student;");
            Console.WriteLine("I think it was to see my mother\'s wedding.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Indeed, my lord, it follow\'d hard upon.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Thrift, thrift, Horatio! the funeral baked meats");
            Console.WriteLine("Did coldly furnish forth the marriage tables.");
            Console.WriteLine("Would I had met my dearest foe in heaven");
            Console.WriteLine("Or ever I had seen that day, Horatio!");
            Console.WriteLine("My father!--methinks I see my father.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Where, my lord?");
            Console.WriteLine("HAMLET");
            Console.WriteLine("In my mind\'s eye, Horatio.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("I saw him once; he was a goodly king.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("He was a man, take him for all in all,");
            Console.WriteLine("I shall not look upon his like again.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("My lord, I think I saw him yesternight.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Saw? who?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("My lord, the king your father.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("The king my father!");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Season your admiration for awhile");
            Console.WriteLine("With an attent ear, till I may deliver,");
            Console.WriteLine("Upon the witness of these gentlemen,");
            Console.WriteLine("This marvel to you.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("For God\'s love, let me hear.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Two nights together had these gentlemen,");
            Console.WriteLine("Marcellus and Bernardo, on their watch,");
            Console.WriteLine("In the dead vast and middle of the night,");
            Console.WriteLine("Been thus encounter\'d. A figure like your father,");
            Console.WriteLine("Armed at point exactly, cap-a-pe,");
            Console.WriteLine("Appears before them, and with solemn march");
            Console.WriteLine("Goes slow and stately by them: thrice he walk\'d");
            Console.WriteLine("By their oppress\'d and fear-surprised eyes,");
            Console.WriteLine("Within his truncheon\'s length; whilst they, distilled");
            Console.WriteLine("Almost to jelly with the act of fear,");
            Console.WriteLine("Stand dumb and speak not to him. This to me");
            Console.WriteLine("In dreadful secrecy impart they did;");
            Console.WriteLine("And I with them the third night kept the watch;");
            Console.WriteLine("Where, as they had deliver\'d, both in time,");
            Console.WriteLine("Form of the thing, each word made true and good,");
            Console.WriteLine("The apparition comes: I knew your father;");
            Console.WriteLine("These hands are not more like.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("But where was this?");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("My lord, upon the platform where we watch\'d.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Did you not speak to it?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("My lord, I did;");
            Console.WriteLine("But answer made it none: yet once methought");
            Console.WriteLine("It lifted up its head and did address");
            Console.WriteLine("Itself to motion, like as it would speak;");
            Console.WriteLine("But even then the morning cock crew loud,");
            Console.WriteLine("And at the sound it shrunk in haste away,");
            Console.WriteLine("And vanish\'d from our sight.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("\'Tis very strange.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("As I do live, my honour\'d lord, \'tis true;");
            Console.WriteLine("And we did think it writ down in our duty");
            Console.WriteLine("To let you know of it.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Indeed, indeed, sirs, but this troubles me.");
            Console.WriteLine("Hold you the watch to-night?");
            Console.WriteLine("MARCELLUS BERNARDO");
            Console.WriteLine("We do, my lord.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Arm\'d, say you?");
            Console.WriteLine("MARCELLUS BERNARDO");
            Console.WriteLine("Arm\'d, my lord.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("From top to toe?");
            Console.WriteLine("MARCELLUS BERNARDO");
            Console.WriteLine("My lord, from head to foot.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Then saw you not his face?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("O, yes, my lord; he wore his beaver up.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("What, look\'d he frowningly?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("A countenance more in sorrow than in anger.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Pale or red?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Nay, very pale.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("And fix\'d his eyes upon you?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Most constantly.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I would I had been there.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("It would have much amazed you.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Very like, very like. Stay\'d it long?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("While one with moderate haste might tell a hundred.");
            Console.WriteLine("MARCELLUS BERNARDO");
            Console.WriteLine("Longer, longer.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Not when I saw\'t.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("His beard was grizzled--no?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("It was, as I have seen it in his life,");
            Console.WriteLine("A sable silver\'d.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I will watch to-night;");
            Console.WriteLine("Perchance \'twill walk again.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("I warrant it will.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("If it assume my noble father\'s person,");
            Console.WriteLine("I\'ll speak to it, though hell itself should gape");
            Console.WriteLine("And bid me hold my peace. I pray you all,");
            Console.WriteLine("If you have hitherto conceal\'d this sight,");
            Console.WriteLine("Let it be tenable in your silence still;");
            Console.WriteLine("And whatsoever else shall hap to-night,");
            Console.WriteLine("Give it an understanding, but no tongue:");
            Console.WriteLine("I will requite your loves. So, fare you well:");
            Console.WriteLine("Upon the platform, \'twixt eleven and twelve,");
            Console.WriteLine("I\'ll visit you.");
            Console.WriteLine("All");
            Console.WriteLine("Our duty to your honour.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Your loves, as mine to you: farewell.");
            Console.WriteLine("Exeunt all but HAMLET");
            Console.WriteLine("");
            Console.WriteLine("My father\'s spirit in arms! all is not well;");
            Console.WriteLine("I doubt some foul play: would the night were come!");
            Console.WriteLine("Till then sit still, my soul: foul deeds will rise,");
            Console.WriteLine("Though all the earth o\'erwhelm them, to men\'s eyes.");
            Console.WriteLine("Exit");
            Console.WriteLine("");
            Console.WriteLine("SCENE III. A room in Polonius\' house.");
            Console.WriteLine("");
            Console.WriteLine("Enter LAERTES and OPHELIA");
            Console.WriteLine("LAERTES");
            Console.WriteLine("My necessaries are embark\'d: farewell:");
            Console.WriteLine("And, sister, as the winds give benefit");
            Console.WriteLine("And convoy is assistant, do not sleep,");
            Console.WriteLine("But let me hear from you.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("Do you doubt that?");
            Console.WriteLine("LAERTES");
            Console.WriteLine("For Hamlet and the trifling of his favour,");
            Console.WriteLine("Hold it a fashion and a toy in blood,");
            Console.WriteLine("A violet in the youth of primy nature,");
            Console.WriteLine("Forward, not permanent, sweet, not lasting,");
            Console.WriteLine("The perfume and suppliance of a minute; No more.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("No more but so?");
            Console.WriteLine("LAERTES");
            Console.WriteLine("Think it no more;");
            Console.WriteLine("For nature, crescent, does not grow alone");
            Console.WriteLine("In thews and bulk, but, as this temple waxes,");
            Console.WriteLine("The inward service of the mind and soul");
            Console.WriteLine("Grows wide withal. Perhaps he loves you now,");
            Console.WriteLine("And now no soil nor cautel doth besmirch");
            Console.WriteLine("The virtue of his will: but you must fear,");
            Console.WriteLine("His greatness weigh\'d, his will is not his own;");
            Console.WriteLine("For he himself is subject to his birth:");
            Console.WriteLine("He may not, as unvalued persons do,");
            Console.WriteLine("Carve for himself; for on his choice depends");
            Console.WriteLine("The safety and health of this whole state;");
            Console.WriteLine("And therefore must his choice be circumscribed");
            Console.WriteLine("Unto the voice and yielding of that body");
            Console.WriteLine("Whereof he is the head. Then if he says he loves you,");
            Console.WriteLine("It fits your wisdom so far to believe it");
            Console.WriteLine("As he in his particular act and place");
            Console.WriteLine("May give his saying deed; which is no further");
            Console.WriteLine("Than the main voice of Denmark goes withal.");
            Console.WriteLine("Then weigh what loss your honour may sustain,");
            Console.WriteLine("If with too credent ear you list his songs,");
            Console.WriteLine("Or lose your heart, or your chaste treasure open");
            Console.WriteLine("To his unmaster\'d importunity.");
            Console.WriteLine("Fear it, Ophelia, fear it, my dear sister,");
            Console.WriteLine("And keep you in the rear of your affection,");
            Console.WriteLine("Out of the shot and danger of desire.");
            Console.WriteLine("The chariest maid is prodigal enough,");
            Console.WriteLine("If she unmask her beauty to the moon:");
            Console.WriteLine("Virtue itself \'scapes not calumnious strokes:");
            Console.WriteLine("The canker galls the infants of the spring,");
            Console.WriteLine("Too oft before their buttons be disclosed,");
            Console.WriteLine("And in the morn and liquid dew of youth");
            Console.WriteLine("Contagious blastments are most imminent.");
            Console.WriteLine("Be wary then; best safety lies in fear:");
            Console.WriteLine("Youth to itself rebels, though none else near.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("I shall the effect of this good lesson keep,");
            Console.WriteLine("As watchman to my heart. But, good my brother,");
            Console.WriteLine("Do not, as some ungracious pastors do,");
            Console.WriteLine("Show me the steep and thorny way to heaven;");
            Console.WriteLine("Whiles, like a puff\'d and reckless libertine,");
            Console.WriteLine("Himself the primrose path of dalliance treads,");
            Console.WriteLine("And recks not his own rede.");
            Console.WriteLine("LAERTES");
            Console.WriteLine("O, fear me not.");
            Console.WriteLine("I stay too long: but here my father comes.");
            Console.WriteLine("Enter POLONIUS");
            Console.WriteLine("");
            Console.WriteLine("A double blessing is a double grace,");
            Console.WriteLine("Occasion smiles upon a second leave.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("Yet here, Laertes! aboard, aboard, for shame!");
            Console.WriteLine("The wind sits in the shoulder of your sail,");
            Console.WriteLine("And you are stay\'d for. There; my blessing with thee!");
            Console.WriteLine("And these few precepts in thy memory");
            Console.WriteLine("See thou character. Give thy thoughts no tongue,");
            Console.WriteLine("Nor any unproportioned thought his act.");
            Console.WriteLine("Be thou familiar, but by no means vulgar.");
            Console.WriteLine("Those friends thou hast, and their adoption tried,");
            Console.WriteLine("Grapple them to thy soul with hoops of steel;");
            Console.WriteLine("But do not dull thy palm with entertainment");
            Console.WriteLine("Of each new-hatch\'d, unfledged comrade. Beware");
            Console.WriteLine("Of entrance to a quarrel, but being in,");
            Console.WriteLine("Bear\'t that the opposed may beware of thee.");
            Console.WriteLine("Give every man thy ear, but few thy voice;");
            Console.WriteLine("Take each man\'s censure, but reserve thy judgment.");
            Console.WriteLine("Costly thy habit as thy purse can buy,");
            Console.WriteLine("But not express\'d in fancy; rich, not gaudy;");
            Console.WriteLine("For the apparel oft proclaims the man,");
            Console.WriteLine("And they in France of the best rank and station");
            Console.WriteLine("Are of a most select and generous chief in that.");
            Console.WriteLine("Neither a borrower nor a lender be;");
            Console.WriteLine("For loan oft loses both itself and friend,");
            Console.WriteLine("And borrowing dulls the edge of husbandry.");
            Console.WriteLine("This above all: to thine ownself be true,");
            Console.WriteLine("And it must follow, as the night the day,");
            Console.WriteLine("Thou canst not then be false to any man.");
            Console.WriteLine("Farewell: my blessing season this in thee!");
            Console.WriteLine("LAERTES");
            Console.WriteLine("Most humbly do I take my leave, my lord.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("The time invites you; go; your servants tend.");
            Console.WriteLine("LAERTES");
            Console.WriteLine("Farewell, Ophelia; and remember well");
            Console.WriteLine("What I have said to you.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("\'Tis in my memory lock\'d,");
            Console.WriteLine("And you yourself shall keep the key of it.");
            Console.WriteLine("LAERTES");
            Console.WriteLine("Farewell.");
            Console.WriteLine("Exit");
            Console.WriteLine("");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("What is\'t, Ophelia, be hath said to you?");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("So please you, something touching the Lord Hamlet.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("Marry, well bethought:");
            Console.WriteLine("\'Tis told me, he hath very oft of late");
            Console.WriteLine("Given private time to you; and you yourself");
            Console.WriteLine("Have of your audience been most free and bounteous:");
            Console.WriteLine("If it be so, as so \'tis put on me,");
            Console.WriteLine("And that in way of caution, I must tell you,");
            Console.WriteLine("You do not understand yourself so clearly");
            Console.WriteLine("As it behoves my daughter and your honour.");
            Console.WriteLine("What is between you? give me up the truth.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("He hath, my lord, of late made many tenders");
            Console.WriteLine("Of his affection to me.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("Affection! pooh! you speak like a green girl,");
            Console.WriteLine("Unsifted in such perilous circumstance.");
            Console.WriteLine("Do you believe his tenders, as you call them?");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("I do not know, my lord, what I should think.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("Marry, I\'ll teach you: think yourself a baby;");
            Console.WriteLine("That you have ta\'en these tenders for true pay,");
            Console.WriteLine("Which are not sterling. Tender yourself more dearly;");
            Console.WriteLine("Or--not to crack the wind of the poor phrase,");
            Console.WriteLine("Running it thus--you\'ll tender me a fool.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("My lord, he hath importuned me with love");
            Console.WriteLine("In honourable fashion.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("Ay, fashion you may call it; go to, go to.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("And hath given countenance to his speech, my lord,");
            Console.WriteLine("With almost all the holy vows of heaven.");
            Console.WriteLine("LORD POLONIUS");
            Console.WriteLine("Ay, springes to catch woodcocks. I do know,");
            Console.WriteLine("When the blood burns, how prodigal the soul");
            Console.WriteLine("Lends the tongue vows: these blazes, daughter,");
            Console.WriteLine("Giving more light than heat, extinct in both,");
            Console.WriteLine("Even in their promise, as it is a-making,");
            Console.WriteLine("You must not take for fire. From this time");
            Console.WriteLine("Be somewhat scanter of your maiden presence;");
            Console.WriteLine("Set your entreatments at a higher rate");
            Console.WriteLine("Than a command to parley. For Lord Hamlet,");
            Console.WriteLine("Believe so much in him, that he is young");
            Console.WriteLine("And with a larger tether may he walk");
            Console.WriteLine("Than may be given you: in few, Ophelia,");
            Console.WriteLine("Do not believe his vows; for they are brokers,");
            Console.WriteLine("Not of that dye which their investments show,");
            Console.WriteLine("But mere implorators of unholy suits,");
            Console.WriteLine("Breathing like sanctified and pious bawds,");
            Console.WriteLine("The better to beguile. This is for all:");
            Console.WriteLine("I would not, in plain terms, from this time forth,");
            Console.WriteLine("Have you so slander any moment leisure,");
            Console.WriteLine("As to give words or talk with the Lord Hamlet.");
            Console.WriteLine("Look to\'t, I charge you: come your ways.");
            Console.WriteLine("OPHELIA");
            Console.WriteLine("I shall obey, my lord.");
            Console.WriteLine("Exeunt");
            Console.WriteLine("");
            Console.WriteLine("SCENE IV. The platform.");
            Console.WriteLine("");
            Console.WriteLine("Enter HAMLET, HORATIO, and MARCELLUS");
            Console.WriteLine("HAMLET");
            Console.WriteLine("The air bites shrewdly; it is very cold.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("It is a nipping and an eager air.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("What hour now?");
            Console.WriteLine("HORATIO");
            Console.WriteLine("I think it lacks of twelve.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("No, it is struck.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Indeed? I heard it not: then it draws near the season");
            Console.WriteLine("Wherein the spirit held his wont to walk.");
            Console.WriteLine("A flourish of trumpets, and ordnance shot off, within");
            Console.WriteLine("");
            Console.WriteLine("What does this mean, my lord?");
            Console.WriteLine("HAMLET");
            Console.WriteLine("The king doth wake to-night and takes his rouse,");
            Console.WriteLine("Keeps wassail, and the swaggering up-spring reels;");
            Console.WriteLine("And, as he drains his draughts of Rhenish down,");
            Console.WriteLine("The kettle-drum and trumpet thus bray out");
            Console.WriteLine("The triumph of his pledge.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Is it a custom?");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Ay, marry, is\'t:");
            Console.WriteLine("But to my mind, though I am native here");
            Console.WriteLine("And to the manner born, it is a custom");
            Console.WriteLine("More honour\'d in the breach than the observance.");
            Console.WriteLine("This heavy-headed revel east and west");
            Console.WriteLine("Makes us traduced and tax\'d of other nations:");
            Console.WriteLine("They clepe us drunkards, and with swinish phrase");
            Console.WriteLine("Soil our addition; and indeed it takes");
            Console.WriteLine("From our achievements, though perform\'d at height,");
            Console.WriteLine("The pith and marrow of our attribute.");
            Console.WriteLine("So, oft it chances in particular men,");
            Console.WriteLine("That for some vicious mole of nature in them,");
            Console.WriteLine("As, in their birth--wherein they are not guilty,");
            Console.WriteLine("Since nature cannot choose his origin--");
            Console.WriteLine("By the o\'ergrowth of some complexion,");
            Console.WriteLine("Oft breaking down the pales and forts of reason,");
            Console.WriteLine("Or by some habit that too much o\'er-leavens");
            Console.WriteLine("The form of plausive manners, that these men,");
            Console.WriteLine("Carrying, I say, the stamp of one defect,");
            Console.WriteLine("Being nature\'s livery, or fortune\'s star,--");
            Console.WriteLine("Their virtues else--be they as pure as grace,");
            Console.WriteLine("As infinite as man may undergo--");
            Console.WriteLine("Shall in the general censure take corruption");
            Console.WriteLine("From that particular fault: the dram of eale");
            Console.WriteLine("Doth all the noble substance of a doubt");
            Console.WriteLine("To his own scandal.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Look, my lord, it comes!");
            Console.WriteLine("Enter Ghost");
            Console.WriteLine("");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Angels and ministers of grace defend us!");
            Console.WriteLine("Be thou a spirit of health or goblin damn\'d,");
            Console.WriteLine("Bring with thee airs from heaven or blasts from hell,");
            Console.WriteLine("Be thy intents wicked or charitable,");
            Console.WriteLine("Thou comest in such a questionable shape");
            Console.WriteLine("That I will speak to thee: I\'ll call thee Hamlet,");
            Console.WriteLine("King, father, royal Dane: O, answer me!");
            Console.WriteLine("Let me not burst in ignorance; but tell");
            Console.WriteLine("Why thy canonized bones, hearsed in death,");
            Console.WriteLine("Have burst their cerements; why the sepulchre,");
            Console.WriteLine("Wherein we saw thee quietly inurn\'d,");
            Console.WriteLine("Hath oped his ponderous and marble jaws,");
            Console.WriteLine("To cast thee up again. What may this mean,");
            Console.WriteLine("That thou, dead corse, again in complete steel");
            Console.WriteLine("Revisit\'st thus the glimpses of the moon,");
            Console.WriteLine("Making night hideous; and we fools of nature");
            Console.WriteLine("So horridly to shake our disposition");
            Console.WriteLine("With thoughts beyond the reaches of our souls?");
            Console.WriteLine("Say, why is this? wherefore? what should we do?");
            Console.WriteLine("Ghost beckons HAMLET");
            Console.WriteLine("");
            Console.WriteLine("HORATIO");
            Console.WriteLine("It beckons you to go away with it,");
            Console.WriteLine("As if it some impartment did desire");
            Console.WriteLine("To you alone.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Look, with what courteous action");
            Console.WriteLine("It waves you to a more removed ground:");
            Console.WriteLine("But do not go with it.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("No, by no means.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("It will not speak; then I will follow it.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Do not, my lord.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Why, what should be the fear?");
            Console.WriteLine("I do not set my life in a pin\'s fee;");
            Console.WriteLine("And for my soul, what can it do to that,");
            Console.WriteLine("Being a thing immortal as itself?");
            Console.WriteLine("It waves me forth again: I\'ll follow it.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("What if it tempt you toward the flood, my lord,");
            Console.WriteLine("Or to the dreadful summit of the cliff");
            Console.WriteLine("That beetles o\'er his base into the sea,");
            Console.WriteLine("And there assume some other horrible form,");
            Console.WriteLine("Which might deprive your sovereignty of reason");
            Console.WriteLine("And draw you into madness? think of it:");
            Console.WriteLine("The very place puts toys of desperation,");
            Console.WriteLine("Without more motive, into every brain");
            Console.WriteLine("That looks so many fathoms to the sea");
            Console.WriteLine("And hears it roar beneath.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("It waves me still.");
            Console.WriteLine("Go on; I\'ll follow thee.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("You shall not go, my lord.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Hold off your hands.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Be ruled; you shall not go.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("My fate cries out,");
            Console.WriteLine("And makes each petty artery in this body");
            Console.WriteLine("As hardy as the Nemean lion\'s nerve.");
            Console.WriteLine("Still am I call\'d. Unhand me, gentlemen.");
            Console.WriteLine("By heaven, I\'ll make a ghost of him that lets me!");
            Console.WriteLine("I say, away! Go on; I\'ll follow thee.");
            Console.WriteLine("Exeunt Ghost and HAMLET");
            Console.WriteLine("");
            Console.WriteLine("HORATIO");
            Console.WriteLine("He waxes desperate with imagination.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Let\'s follow; \'tis not fit thus to obey him.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Have after. To what issue will this come?");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Something is rotten in the state of Denmark.");
            Console.WriteLine("HORATIO");
            Console.WriteLine("Heaven will direct it.");
            Console.WriteLine("MARCELLUS");
            Console.WriteLine("Nay, let\'s follow him.");
            Console.WriteLine("Exeunt");
            Console.WriteLine("");
            Console.WriteLine("SCENE V. Another part of the platform.");
            Console.WriteLine("");
            Console.WriteLine("Enter GHOST and HAMLET");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Where wilt thou lead me? speak; I\'ll go no further.");
            Console.WriteLine("Ghost");
            Console.WriteLine("Mark me.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("I will.");
            Console.WriteLine("Ghost");
            Console.WriteLine("My hour is almost come,");
            Console.WriteLine("When I to sulphurous and tormenting flames");
            Console.WriteLine("Must render up myself.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Alas, poor ghost!");
            Console.WriteLine("Ghost");
            Console.WriteLine("Pity me not, but lend thy serious hearing");
            Console.WriteLine("To what I shall unfold.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Speak; I am bound to hear.");
            Console.WriteLine("Ghost");
            Console.WriteLine("So art thou to revenge, when thou shalt hear.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("What?");
            Console.WriteLine("Ghost");
            Console.WriteLine("I am thy father\'s spirit,");
            Console.WriteLine("Doom\'d for a certain term to walk the night,");
            Console.WriteLine("And for the day confined to fast in fires,");
            Console.WriteLine("Till the foul crimes done in my days of nature");
            Console.WriteLine("Are burnt and purged away. But that I am forbid");
            Console.WriteLine("To tell the secrets of my prison-house,");
            Console.WriteLine("I could a tale unfold whose lightest word");
            Console.WriteLine("Would harrow up thy soul, freeze thy young blood,");
            Console.WriteLine("Make thy two eyes, like stars, start from their spheres,");
            Console.WriteLine("Thy knotted and combined locks to part");
            Console.WriteLine("And each particular hair to stand on end,");
            Console.WriteLine("Like quills upon the fretful porpentine:");
            Console.WriteLine("But this eternal blazon must not be");
            Console.WriteLine("To ears of flesh and blood. List, list, O, list!");
            Console.WriteLine("If thou didst ever thy dear father love--");
            Console.WriteLine("HAMLET");
            Console.WriteLine("O God!");
            Console.WriteLine("Ghost");
            Console.WriteLine("Revenge his foul and most unnatural murder.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Murder!");
            Console.WriteLine("Ghost");
            Console.WriteLine("Murder most foul, as in the best it is;");
            Console.WriteLine("But this most foul, strange and unnatural.");
            Console.WriteLine("HAMLET");
            Console.WriteLine("Haste me to know\'t, that I, with wings as swift");
            Console.WriteLine("As meditation or the thoughts of love,");
            Console.WriteLine("May sweep to my revenge.");
            Console.WriteLine("Ghost");
            Console.WriteLine("I find thee apt;");
            Console.WriteLine("And duller shouldst thou be than the fat weed");
            Console.WriteLine("That roots itself in ease on Lethe wharf,");
            Console.WriteLine("Wouldst thou not stir in this. Now, Hamlet, hear:");
            Console.WriteLine("\'Tis given out that, sleeping in my orchard,");
            Console.WriteLine("A serpent stung me; so the whole ear of Denmark");
            Console.WriteLine("Is by a forged process of my death");
            Console.WriteLine("Rankly abused: but know, thou noble youth,");
        }		

    }
}
